<?php
/**
 * CreateSettingResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * configapi
 *
 * Config API lets you easily manage configuration at scale.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CreateSettingResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description Result of performing a create setting operation
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateSettingResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CreateSettingResponse"
     */
    public function testCreateSettingResponse()
    {
    }

    /**
     * Test attribute "successful"
     */
    public function testPropertySuccessful()
    {
    }

    /**
     * Test attribute "setting_definition_id"
     */
    public function testPropertySettingDefinitionId()
    {
    }

    /**
     * Test attribute "setting_value_id"
     */
    public function testPropertySettingValueId()
    {
    }

    /**
     * Test attribute "error_message"
     */
    public function testPropertyErrorMessage()
    {
    }
}
