<?php
/**
 * HttpWwwFormUrlEncodedParameterTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * configapi
 *
 * Config API lets you easily manage configuration at scale.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * HttpWwwFormUrlEncodedParameterTest Class Doc Comment
 *
 * @category    Class */
// * @description Defines an x-www-form-urlencoded parameter
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class HttpWwwFormUrlEncodedParameterTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "HttpWwwFormUrlEncodedParameter"
     */
    public function testHttpWwwFormUrlEncodedParameter()
    {
    }

    /**
     * Test attribute "key_name"
     */
    public function testPropertyKeyName()
    {
    }

    /**
     * Test attribute "key_value"
     */
    public function testPropertyKeyValue()
    {
    }

    /**
     * Test attribute "use_output_from_previous_task"
     */
    public function testPropertyUseOutputFromPreviousTask()
    {
    }
}
