<?php
/**
 * HttpRawTextParameterTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * configapi
 *
 * Config API lets you easily manage configuration at scale.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.32
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * HttpRawTextParameterTest Class Doc Comment
 *
 * @category    Class
 * @description Raw text parameter that defines the entire body of the HTTP payload; cannot be used with other parameter types
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class HttpRawTextParameterTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "HttpRawTextParameter"
     */
    public function testHttpRawTextParameter()
    {
    }

    /**
     * Test attribute "parameter_value"
     */
    public function testPropertyParameterValue()
    {
    }

    /**
     * Test attribute "use_output_from_previous_task"
     */
    public function testPropertyUseOutputFromPreviousTask()
    {
    }
}
