<?php
/**
 * HttpOrchestrationTaskTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * configapi
 *
 * Config API lets you easily manage configuration at scale.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * HttpOrchestrationTaskTest Class Doc Comment
 *
 * @category    Class */
// * @description HttpOrchestrationTask
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class HttpOrchestrationTaskTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "HttpOrchestrationTask"
     */
    public function testHttpOrchestrationTask()
    {
    }

    /**
     * Test attribute "task_name"
     */
    public function testPropertyTaskName()
    {
    }

    /**
     * Test attribute "http_method"
     */
    public function testPropertyHttpMethod()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "http_headers"
     */
    public function testPropertyHttpHeaders()
    {
    }

    /**
     * Test attribute "query_parameters"
     */
    public function testPropertyQueryParameters()
    {
    }

    /**
     * Test attribute "form_data_parameters"
     */
    public function testPropertyFormDataParameters()
    {
    }

    /**
     * Test attribute "www_form_url_encoded_parameters"
     */
    public function testPropertyWwwFormUrlEncodedParameters()
    {
    }

    /**
     * Test attribute "raw_text_body"
     */
    public function testPropertyRawTextBody()
    {
    }

    /**
     * Test attribute "raw_binary_body"
     */
    public function testPropertyRawBinaryBody()
    {
    }
}
