<?php
/**
 * SettingValueTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * configapi
 *
 * Config API lets you easily manage configuration at scale.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SettingValueTest Class Doc Comment
 *
 * @category    Class */
// * @description Value of a setting
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SettingValueTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SettingValue"
     */
    public function testSettingValue()
    {
    }

    /**
     * Test attribute "config_setting_value_id"
     */
    public function testPropertyConfigSettingValueId()
    {
    }

    /**
     * Test attribute "config_setting_definition_id"
     */
    public function testPropertyConfigSettingDefinitionId()
    {
    }

    /**
     * Test attribute "config_setting_value"
     */
    public function testPropertyConfigSettingValue()
    {
    }

    /**
     * Test attribute "config_setting_last_modified"
     */
    public function testPropertyConfigSettingLastModified()
    {
    }

    /**
     * Test attribute "config_setting_name"
     */
    public function testPropertyConfigSettingName()
    {
    }

    /**
     * Test attribute "config_setting_description"
     */
    public function testPropertyConfigSettingDescription()
    {
    }

    /**
     * Test attribute "config_setting_tags"
     */
    public function testPropertyConfigSettingTags()
    {
    }

    /**
     * Test attribute "config_setting_type"
     */
    public function testPropertyConfigSettingType()
    {
    }
}
